### PR TITLE
feature: distro- (20.04 -> 22.04) + version bump

### PR DESCRIPTION
**Pull request by robot-o**
- upgrade to latest LTS release (focal (20.04) -> jammy (22.04))
- bump package versions to latest stable

### CODE REVIEW

**Comment by robot-o** [comment]
@hajowieland since there isn't a github action / ci for this image, is docker hub configured to pull main and rebuild, or do you do that manually? do you want me to make another PR for a pipeline if that's the case?

**Comment by hajowieland** [comment]
lgtm, thanks for your PR!

**Comment by hajowieland** [comment]
> @hajowieland since there isn't a github action / ci for this image, is docker hub configured to pull main and rebuild, or do you do that manually? do you want me to make another PR for a pipeline if that's the case?

Currently there is no automatic build for the image - if you want to implement this process, go for it :)

**Review by hajowieland — APPROVED** [review]
LGTM

**Pull request merged**
